{
	"name": "Sht31",
	"speakableName": "temperature",
	"version": "0.0.1",
	"icon": "fab fa-battle-net",
	"category": "alice",
	"author": "Marcel-65",
	"maintainers": [
	       "Marcel-65"
	       ],
	"desc": "What is the temperature",
	"aliceMinVersion": "1.0.0-b3",
	"pipRequirements": [
		""
	],
	"systemRequirements": [
		""
	],
	"conditions": {
		"lang": [
			"en"
		],
		"online": true,
		"asrArbitraryCapture": true,
		"activeManager": [
			"Sht31"
		]
	}
}
